apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: nginx
    name: nginx
  spec:
    ports:
    - port: 80
      nodePort: 30080
      targetPort: nginx-httpport
      protocol: TCP
    selector:
      service: nginx
    type: NodePort

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      service: nginx
    name: nginx
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          service: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
          - name: nginx-httpport
            containerPort: 80
            protocol: TCP
        restartPolicy: Always